
import type { Episode, Category } from '@/types';
import { Microscope, Eye, Glasses, TrendingUp, Briefcase, Smile, LayoutGrid, Activity, Users } from 'lucide-react';

export const placeholderEpisodes: Episode[] = [
  {
    id: '1',
    title: 'The Art of Deep Work in Clinical Practice',
    showName: 'Optometry Edge',
    description: 'Strategies for maintaining focus and productivity in a busy optometric practice.',
    duration: '45:22',
    thumbnailUrl: 'https://placehold.co/600x600.png',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', 
    releaseDate: '2024-07-15',
    category: 'practice-growth',
  },
  {
    id: '2',
    title: 'Mindfulness for Optometrists',
    showName: 'Clear Vision Wellness',
    description: 'Simple mindfulness exercises to reduce stress and enhance well-being for eye care professionals.',
    duration: '15:05',
    thumbnailUrl: 'https://placehold.co/600x600.png',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    releaseDate: '2024-07-14',
    category: 'practitioner-wellness',
  },
  {
    id: '3',
    title: 'Innovative Clinic Design',
    showName: 'Practice Builders',
    description: 'Exploring creative approaches to optometry clinic design and patient experience.',
    duration: '55:10',
    thumbnailUrl: 'https://placehold.co/600x600.png',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    releaseDate: '2024-07-12',
    category: 'professional-dev',
  },
  {
    id: '4',
    title: 'Latest in OCT Technology',
    showName: 'Optical Innovations',
    description: 'A deep dive into the newest advancements in Optical Coherence Tomography and their clinical applications.',
    duration: '35:40',
    thumbnailUrl: 'https://placehold.co/600x600.png',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    releaseDate: '2024-07-10',
    category: 'optical-tech',
  },
  {
    id: '5',
    title: 'Building a Patient-Centric Practice',
    showName: 'The Modern Optometrist',
    description: 'Strategies for practice growth focusing on patient retention and referrals.',
    duration: '62:30',
    thumbnailUrl: 'https://placehold.co/600x600.png',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    releaseDate: '2024-07-08',
    category: 'practice-growth',
  },
  {
    id: '6',
    title: 'Phosphene Phenomena',
    showName: 'Focus Bites',
    description: 'Episode 1 of Focus Bites, exploring the fascinating world of phosphene phenomena and what they tell us about our visual system.',
    duration: '08:17',
    thumbnailUrl: 'https://placehold.co/600x600.png',
    audioUrl: 'https://github.com/Phantozweb/StromVault/blob/5d97da6c8163ba0593557434f5c3b5d1a5ed2fb9/Focus%20bites/focus-bites-ep1-phosphene-phenomena.mp3',
    releaseDate: '2024-07-26',
    category: 'vision-science',
  },
];

export const placeholderCategories: Category[] = [
  { id: 'clinical-insights', name: 'Clinical Insights', icon: Microscope, imageUrl: 'https://placehold.co/400x300.png' , dataAiHint: 'abstract pattern' },
  { id: 'vision-science', name: 'Vision Science', icon: Eye, imageUrl: 'https://placehold.co/400x300.png', dataAiHint: 'geometric design' },
  { id: 'optical-tech', name: 'Optical Technology', icon: Glasses, imageUrl: 'https://placehold.co/400x300.png', dataAiHint: 'tech background' },
  { id: 'practice-growth', name: 'Practice Growth', icon: TrendingUp, imageUrl: 'https://placehold.co/400x300.png', dataAiHint: 'business chart' },
  { id: 'patient-care', name: 'Patient Care', icon: Users, imageUrl: 'https://placehold.co/400x300.png', dataAiHint: 'people interaction' },
  { id: 'ocular-health', name: 'Ocular Health', icon: Activity, imageUrl: 'https://placehold.co/400x300.png', dataAiHint: 'medical abstract' },
  { id: 'professional-dev', name: 'Professional Development', icon: Briefcase, imageUrl: 'https://placehold.co/400x300.png', dataAiHint: 'learning concept' },
  { id: 'practitioner-wellness', name: 'Practitioner Wellness', icon: Smile, imageUrl: 'https://placehold.co/400x300.png', dataAiHint: 'calm nature' },
  { id: 'all-episodes', name: 'All Episodes', icon: LayoutGrid, imageUrl: 'https://placehold.co/400x300.png', dataAiHint: 'grid pattern' },
];
